name: auto-package
run-name: ${{ github.actor }} is auto-packaging a wheel
on: [push]
jobs:
  auto-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f plugin_requirements.txt ]; then pip install -r plugin_requirements.txt; fi
      - name: Build wheel
        run: |
          python -m pip install --upgrade build
          python -m build 
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python-version }}-wheel
          path: dist/*
     
